### PR TITLE
Updated the version of the toolkit used.

### PR DESCRIPTION
**Pull request by 0xOmarA**
This PR updates the version of the toolkit used to handle the decoding of enum discrims from both integers and strings.

### CODE REVIEW

**Comment by fpieper** [comment]
@0xOmarA Thank you 👍 

@Krulknul can you please take a look and see whether this resolves all dependencies on our fork? #14 and #15 were the first part. Let me know if you have questions, thx

**Comment by dhedey** [comment]
Thanks @fpieper. Sorry for dropping this one, was on annual leave.

@0xOmarA  has performed the following tests:
* Checked the toolkit works with both old (broken) and new (consistent) Gateway JSON formats, as per the unit tests here: [https://github.com/radixdlt/radix-engine-toolkit/blob/7de47f829d08ad8c3a69ac69dad4[…]ddd94ae22a8/crates/sbor-json/tests/programmatic_scrypto_sbor.rs](https://github.com/radixdlt/radix-engine-toolkit/blob/7de47f829d08ad8c3a69ac69dad44ddd94ae22a8/crates/sbor-json/tests/programmatic_scrypto_sbor.rs#L202-L266)
* Validated that the radix event stream test case passes with `cargo run -p examples --bin minimal`

Is this enough to proceed with publishing, so we can advertise the new version in our announcements / mailings?

**Comment by Krulknul** [comment]
I have confirmed that this works both on `mainnet.radixdlt.com` (old gateway) and `stokenet.radixdlt.com` (new gateway), where it would previously fail on `stokenet.radixdlt.com`. Thank you very much for this PR.

For the future though, I don't think it's realistic for radix-event-stream to work across gateway versions, as new gateway versions could easily break its transaction fetching mechanism.

I would tend to say that users should run their own gateway so their service won't break when the public gateway is upgraded, and then they can upgrade together with radix-event-stream when they're ready. But there's a whole discussion to be had here which includes how to version the transaction sources and also the radix-client repository which radix-event-stream depends on.

I will now merge this and release a new version. Thank you very much again.

**Comment by fpieper** [comment]
@Krulknul thanks for checking 👍

Regarding future compatibility, I think this is fine. There is no need for cross compatibility imo. It would be good ofc to have not many breaking changes in the gateway. But overall if you are using the old gateway you would just stick to the previous version of the event stream a bit longer until a new version of the event stream is being released.

**Pull request merged**
